spring:
  mail:
    host: smtp.gmail.com
    username: truongbb96
    password: nrvhnauwtphaomng
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
